# Path Configuration for SEO Competitive Intelligence Platform
# All paths are relative to the project root unless specified as absolute

# ============================================================================
# BASE DIRECTORIES
# ============================================================================
base:
  project_root: "."
  config_dir: "config"
  source_dir: "src"
  data_dir: "data"
  reports_dir: "reports"
  logs_dir: "logs"
  cache_dir: "cache"
  temp_dir: "temp"
  models_dir: "models"
  exports_dir: "exports"

# ============================================================================
# DATA DIRECTORIES
# ============================================================================
data:
  raw_data: "data"
  processed_data: "data/processed"
  archive_data: "data/archive"
  backup_data: "data/backup"
  
  # Data source specific directories
  semrush_data: "data/semrush"
  ahrefs_data: "data/ahrefs"
  google_analytics_data: "data/google_analytics"
  custom_data: "data/custom"
  
  # Date-based data organization
  current_data: "data/current"
  historical_data: "data/historical"
  
  # Data quality and validation
  validated_data: "data/validated"
  rejected_data: "data/rejected"
  quarantine_data: "data/quarantine"

# ============================================================================
# REPORTS AND OUTPUTS
# ============================================================================
reports:
  base: "reports"
  executive: "reports/executive"
  detailed: "reports/detailed"
  competitive: "reports/competitive"
  technical: "reports/technical"
  
  # Report types
  insights: "reports/insights"
  recommendations: "reports/recommendations"
  visuals: "reports/visuals"
  dashboards: "reports/dashboards"
  
  # Specific report categories
  competitor_threats: "reports/insights/competitor_threats"
  content_opportunities: "reports/insights/content_opportunities"
  ranking_gaps: "reports/insights/ranking_gaps"
  
  # Recommendation categories
  quick_wins: "reports/recommendations/quick_wins"
  long_term_strategies: "reports/recommendations/long_term_strategies"
  risk_mitigations: "reports/recommendations/risk_mitigations"
  
  # Visual categories
  positional_trends: "reports/visuals/positional_trends"
  serp_feature_breakdown: "reports/visuals/serp_feature_breakdown"
  traffic_comparison: "reports/visuals/traffic_comparison"
  competitive_landscape: "reports/visuals/competitive_landscape"

# ============================================================================
# LOGGING DIRECTORIES
# ============================================================================
logs:
  base: "logs"
  application: "logs/application"
  pipeline: "logs/pipeline"
  error: "logs/error"
  audit: "logs/audit"
  performance: "logs/performance"
  
  # Log rotation and archival
  archive: "logs/archive"
  current: "logs/current"
  
  # Component-specific logs
  data_loader: "logs/data_loader"
  feature_engineering: "logs/feature_engineering"
  modeling: "logs/modeling"
  optimization: "logs/optimization"
  exports: "logs/exports"

# ============================================================================
# CACHE AND TEMPORARY DIRECTORIES
# ============================================================================
cache:
  base: "cache"
  data_cache: "cache/data"
  model_cache: "cache/models"
  feature_cache: "cache/features"
  analysis_cache: "cache/analysis"
  visualization_cache: "cache/visualizations"
  
  # Cache by time period
  short_term: "cache/short_term"
  medium_term: "cache/medium_term"
  long_term: "cache/long_term"

temp:
  base: "temp"
  processing: "temp/processing"
  uploads: "temp/uploads"
  downloads: "temp/downloads"
  staging: "temp/staging"

# ============================================================================
# MODEL DIRECTORIES
# ============================================================================
models:
  base: "models"
  trained: "models/trained"
  pretrained: "models/pretrained"
  ensemble: "models/ensemble"
  archived: "models/archived"
  
  # Model types
  position_prediction: "models/position_prediction"
  traffic_optimization: "models/traffic_optimization"
  competitive_analysis: "models/competitive_analysis"
  anomaly_detection: "models/anomaly_detection"
  
  # Model artifacts
  artifacts: "models/artifacts"
  metadata: "models/metadata"
  performance: "models/performance"
  validation: "models/validation"

# ============================================================================
# CONFIGURATION DIRECTORIES
# ============================================================================
config:
  base: "config"
  environments: "config/environments"
  schemas: "config/schemas"
  templates: "config/templates"
  validation: "config/validation"
  
  # Environment-specific configs
  development: "config/environments/development.yaml"
  staging: "config/environments/staging.yaml"
  production: "config/environments/production.yaml"
  
  # Component configurations
  pipelines: "config/pipelines"
  data_sources: "config/data_sources"
  models: "config/models"
  exports: "config/exports"

# ============================================================================
# EXPORT DIRECTORIES
# ============================================================================
exports:
  base: "exports"
  reports: "exports/reports"
  data: "exports/data"
  models: "exports/models"
  visualizations: "exports/visualizations"
  
  # Export formats
  excel: "exports/excel"
  csv: "exports/csv"
  json: "exports/json"
  pdf: "exports/pdf"
  html: "exports/html"
  
  # Time-based exports
  daily: "exports/daily"
  weekly: "exports/weekly"
  monthly: "exports/monthly"
  
  # Client-specific exports
  internal: "exports/internal"
  client: "exports/client"
  public: "exports/public"

# ============================================================================
# EXTERNAL INTEGRATIONS
# ============================================================================
integrations:
  base: "integrations"
  apis: "integrations/apis"
  webhooks: "integrations/webhooks"
  imports: "integrations/imports"
  exports: "integrations/exports"
  
  # Third-party specific
  semrush: "integrations/semrush"
  ahrefs: "integrations/ahrefs"
  google: "integrations/google"
  custom: "integrations/custom"

# ============================================================================
# TESTING DIRECTORIES
# ============================================================================
tests:
  base: "tests"
  unit: "tests/unit"
  integration: "tests/integration"
  fixtures: "tests/fixtures"
  mocks: "tests/mocks"
  
  # Test data
  test_data: "tests/data"
  expected_outputs: "tests/expected_outputs"
  
  # Performance tests
  performance: "tests/performance"
  load: "tests/load"
  stress: "tests/stress"

# ============================================================================
# DOCUMENTATION DIRECTORIES
# ============================================================================
docs:
  base: "docs"
  user_guide: "docs/user_guide"
  api_reference: "docs/api_reference"
  developer_guide: "docs/developer_guide"
  tutorials: "docs/tutorials"
  
  # Generated documentation
  auto_generated: "docs/auto_generated"
  schemas: "docs/schemas"
  examples: "docs/examples"

# ============================================================================
# SECURITY AND CREDENTIALS
# ============================================================================
security:
  credentials: "config/credentials"
  certificates: "config/certificates"
  keys: "config/keys"
  secrets: "config/secrets"
  
  # Note: These directories should be properly secured and potentially excluded from version control
  
# ============================================================================
# BACKUP AND RECOVERY
# ============================================================================
backup:
  base: "backup"
  data: "backup/data"
  models: "backup/models"
  configurations: "backup/configurations"
  reports: "backup/reports"
  
  # Backup frequency
  daily: "backup/daily"
  weekly: "backup/weekly"
  monthly: "backup/monthly"
  
  # Recovery
  recovery: "backup/recovery"
  restore_points: "backup/restore_points"

# ============================================================================
# MONITORING AND ANALYTICS
# ============================================================================
monitoring:
  base: "monitoring"
  metrics: "monitoring/metrics"
  alerts: "monitoring/alerts"
  health_checks: "monitoring/health_checks"
  performance: "monitoring/performance"
  
  # Dashboards
  dashboards: "monitoring/dashboards"
  real_time: "monitoring/real_time"
  historical: "monitoring/historical"
