# Development Environment Configuration
environment:
  name: "development"
  debug: true
  log_level: "DEBUG"
  data_retention_days: 30
  cache_ttl_seconds: 1800  # 30 minutes
  max_concurrent_operations: 2
  enable_detailed_logging: true
  enable_performance_monitoring: true
  enable_debug_features: true

# Development-specific settings
development:
  auto_reload: true
  hot_reload: true
  verbose_errors: true
  show_sql_queries: true
  enable_profiling: true
  mock_external_apis: true
  
# Database configuration for development
database:
  host: "localhost"
  port: 5432
  database: "seo_dev"
  username: "seo_dev_user"
  password: "dev_password_123"
  pool_size: 5
  timeout_seconds: 30
  ssl_enabled: false
  echo_queries: true

# API configuration for development
api:
  base_url: "http://localhost:8000"
  timeout_seconds: 30
  retry_attempts: 2
  enable_mock_responses: true
  rate_limiting_enabled: false
  
# Processing configuration for development
processing:
  chunk_size: 1000  # Smaller chunks for development
  max_memory_usage_gb: 2.0
  parallel_processing: false  # Easier debugging
  max_workers: 1
  enable_data_validation: true
  quality_threshold: 0.6  # Lower threshold for testing
  enable_auto_cleaning: true
  
# Caching for development
caching:
  enabled: true
  backend: "memory"
  default_ttl: 1800
  max_size_mb: 100
  
# Security for development
security:
  csrf_protection: false
  ssl_required: false
  session_secure: false
  
# External services
external_services:
  semrush:
    mock_enabled: true
    timeout: 10
  ahrefs:
    mock_enabled: true
    timeout: 10
  google_analytics:
    mock_enabled: true
    timeout: 15
