# Production Environment Configuration
environment:
  name: "production"
  debug: false
  log_level: "INFO"
  data_retention_days: 365
  cache_ttl_seconds: 3600  # 1 hour
  max_concurrent_operations: 8
  enable_detailed_logging: false
  enable_performance_monitoring: true
  enable_debug_features: false

# Production-specific settings
production:
  auto_reload: false
  hot_reload: false
  verbose_errors: false
  show_sql_queries: false
  enable_profiling: false
  mock_external_apis: false
  
# Database configuration for production
database:
  host: "${DB_HOST}"
  port: 5432
  database: "${DB_NAME}"
  username: "${DB_USER}"
  password: "${DB_PASSWORD}"
  pool_size: 20
  timeout_seconds: 60
  ssl_enabled: true
  echo_queries: false

# API configuration for production
api:
  base_url: "${API_BASE_URL}"
  timeout_seconds: 60
  retry_attempts: 5
  enable_mock_responses: false
  rate_limiting_enabled: true
  
# Processing configuration for production
processing:
  chunk_size: 50000
  max_memory_usage_gb: 16.0
  parallel_processing: true
  max_workers: 8
  enable_data_validation: true
  quality_threshold: 0.8
  enable_auto_cleaning: true
  
# Caching for production
caching:
  enabled: true
  backend: "redis"
  default_ttl: 3600
  max_size_mb: 2048
  
# Security for production
security:
  csrf_protection: true
  ssl_required: true
  session_secure: true
  
# External services
external_services:
  semrush:
    mock_enabled: false
    timeout: 30
    rate_limit: 60
  ahrefs:
    mock_enabled: false
    timeout: 45
    rate_limit: 100
  google_analytics:
    mock_enabled: false
    timeout: 60
    rate_limit: 50

# Monitoring and alerting
monitoring:
  enabled: true
  metrics_collection: true
  error_tracking: true
  performance_monitoring: true
  
alerting:
  enabled: true
  email_notifications: true
  slack_notifications: true
  sms_notifications: false
  
# Backup and recovery
backup:
  enabled: true
  frequency: "daily"
  retention_days: 90
  remote_storage: true
